### PR TITLE
Completed HTML & CSS3 Course Project #7 - Newsweek Clone

### PR DESCRIPTION
**Pull request by Flakster**
### This pull request includes

- A working replica of the Newsweek.com homepage
- Use of Bootstrap classes for positioning and responsiveness
- Use of W3C validator for the markup
- Use of Stylelint linter for checking the CSS style files
- Special care to page layout not breaking on smaller screens
- Issues referenced by TSE on past review already fixed

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi  Carlos!  
### Your project looks :+1: amazing!
Here a few things you need to fix before this project can be approved:

* [ ] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)) Right now your title is not really meaningful, and description should have list of changes you implemented while working on this project.
* [ ] Responsiveness requires some fixing:
* Tablet version
image
* Mobile version
image

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Flakster** [comment]
**This pull request includes**

A working replica of the Newsweek.com  homepage
Use of Bootstrap classes for positioning and responsiveness
Use of W3C validator for the markup
Use of Stylelint linter for cheking the CSS style files
Special care to page layout not breaking on smaller screens
Issues referenced by TSE on past review already fixed

**Review by addod19 — APPROVED** [review]
## Status: Apprpved 🟢

Great job @Flakster . Your project looks amazing. 😄  I will have to approve your project. Good job fixing the comments from previous reviewer. 💯 

You can now merge to master and submit project completion form. 
Good luck in your next project. ✋ 
Happy coding 💻

**Comment by Flakster** [comment]
Hey @pelzolga123  and @addod19 Thanks a lot for your review and comments!

**Pull request merged**
